ADDMatrix_flag: true
FRICTION_marker: fB
MASS_marker: mBNN
camera_info_topic_color: /camera/color/camera_info
camera_info_topic_depth: /camera/depth/camera_info
combine_particle_depth_mask_flag: false
compare_depth_img_vk: true
convolution_size: 0
debug_depth_img_flag: false
depth_diff_value_0_1_alpha: 0.8
depth_diff_value_0_1_flag: true
depth_diff_value_0_1_threshold: 0.03
depth_image_cut_flag: false
depth_mask_flag: false
depth_mask_vk_flag: false
dope_flag: true
draw_wireframe_flag: false
err_file: rayTracing
farVal: 3
gazebo_flag: false
ignore_edge_pixels: false
locate_camera_flag: ar
multiprocessing_flag: false
nearVal: 0.03
obj_friction_mean_dict:
  Ketchup: 0.1
  Mayo: 0.1
  Milk: 0.1
  Mustard: 0.1
  Parmesan: 0.1
  SaladDressing: 0.1
  cracker: 0.1
  soup: 0.1
obj_friction_min_mean_dict:
  Ketchup: 0.001
  Mayo: 0.001
  Milk: 0.001
  Mustard: 0.001
  Parmesan: 0.001
  SaladDressing: 0.001
  cracker: 0.001
  soup: 0.001
obj_friction_noise_flag: true
obj_friction_sigma_dict:
  Ketchup: 0.3
  Mayo: 0.3
  Milk: 0.3
  Mustard: 0.3
  Parmesan: 0.3
  SaladDressing: 0.3
  cracker: 0.3
  soup: 0.3
obj_mass_mean_dict:
  Ketchup: 0.06
  Mayo: 0.06
  Milk: 0.04
  Mustard: 0.05
  Parmesan: 0.035
  SaladDressing: 0.06
  cracker: 0.45
  soup: 0.35
obj_mass_min_mean_dict:
  Ketchup: 0.001
  Mayo: 0.001
  Milk: 0.001
  Mustard: 0.001
  Parmesan: 0.001
  SaladDressing: 0.001
  cracker: 0.001
  soup: 0.001
obj_mass_noise_flag: true
obj_mass_sigma_dict:
  Ketchup: 0.1
  Mayo: 0.1
  Milk: 0.1
  Mustard: 0.1
  Parmesan: 0.1
  SaladDressing: 0.1
  cracker: 0.5
  soup: 0.5
obj_motion_model_ang_noise: 0.05
obj_motion_model_noise_flag: true
obj_motion_model_pos_noise: 0.005
obj_restitution_mean: 0.9
obj_restitution_sigma: 0.2
obj_sigma_ang_for_obs_weight_dict:
  Ketchup: 0.2
  Mayo: 0.2
  Milk: 0.2
  Mustard: 0.2
  Parmesan: 0.2
  SaladDressing: 0.2
  cracker: 0.2
  soup: 0.2
obj_sigma_pos_for_obs_weight_dict:
  Ketchup: 0.1
  Mayo: 0.1
  Milk: 0.1
  Mustard: 0.1
  Parmesan: 0.1
  SaladDressing: 0.1
  cracker: 0.1
  soup: 0.1
object_name_list:
- cracker
- soup
object_num: 2
objs_are_not_touching_target_objs_num: 0
objs_touching_target_objs_num: 0
optitrack_flag: true
ortho_to_persp_flag: true
other_base_obj_num: 0
other_obj_num: 0
oto_name_list:
- base_of_cracker
- shelves
- pringles
otob_name_list:
- cracker_obstacle
- fish_can
panda_robot_link_number: 11
particle_num: 50
persp_to_ortho_flag: false
pick_particle_rate: 0.0
print_flag: false
print_score_flag: false
process_model_flag: normal
ray_tracing_type: multiray
record_results_flag: false
record_time_consumption_flag: false
render_flag: vk
robot_num: 1
run_alg_flag: PBPF
running_model: PBPF_RGBD
show_particle_depth_image_to_point_cloud_flag: false
show_ray: false
sigma_obs_ang_for_init: 0.2
sigma_obs_pos_for_init: 0.02
sigma_obs_z_for_init: 0.02
sim_real_world_flag: true
task_flag: '1'
test_initial_rendered_depth_image_flag: false
update_style_flag: time
use_convolution_flag: false
version: multiray
visibility_compute_separate_flag: true
visibility_compute_vk: true
